Dev
rica213/recipe-app pull request #33
Opened 2023-06-09 19:55 UTC by rica213

Hi, 
My name is Larissa, and this week I was collaborating with [Shaaibu](https://github.com/shaaibu7) ❤️ to implement this project.
It is a project that manages recipes and their corresponding foods. 🥘 
Here is an example of a user experience 👇🏽 
1 - The user starts the application
2 - The user gets to the homepage which is the **Public recipes list** page
3 - The user needs to log in or sign up to access the **Recipes list** page and the **Foods list** page 
4 - In the **Recipe list** page, the user can add, and delete recipe items
5 - In the **Food list** page, the user can add, and delete food items
6 - The user can click on the recipe items in the **Public recipes list** page and **Recipes list** page, and they will be redirected to the **Recipe detail** page
7 - The user sees all the details about a recipe and a table that contains all ingredients necessary for that recipe
8 - If the user is the owner of the recipe, they can set the visibility of the recipe to public or private
9 - If the user is the owner of the recipe, they can **add new ingredient**
10 - The button **add ingredient** which is present in the **recipe detail** will redirect the user to the new **recipe food** page
11 - If the new addition is successful, the user will be redirected to the recipe detail page and can see the new ingredient in the table
11 - The user clicks the **"generate shopping list"**, a page will appear, it will contain all the missing foods that the user needs
12 - If the user enters the wrong URL, they will be redirected to the Homepage.

<img src="https://media3.giphy.com/media/OH4hSoR33Et3OOvpZw/giphy.gif"/>

Happy reviewing, and thank you for your valuable time ❤️

2023-06-09 20:29 UTC, VICTOR-CHUKWU requested changes
Hi @rica213  and @shaaibu7  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 20:29 UTC, VICTOR-CHUKWU commented on app/views/recipes/index.html.erb
> +                <%= button_to 'Remove', recipe, method: :delete %>
- [ ] When I  try deleting a recipe I had an error because I had added it to recipe food
![Screenshot from 2023-06-09 21-12-09](https://github.com/rica213/recipe-app/assets/66097371/ec4fe561-520d-4c8c-971e-38656bf32ae5)

2023-06-09 20:29 UTC, VICTOR-CHUKWU commented on app/views/foods/index.html.erb
> +                    <td><%= button_to 'Delete', food, method: :delete %></td>
- [ ] Also when I try deleting a food that I have added to a recipe food I have an error
![Screenshot from 2023-06-09 21-11-44](https://github.com/rica213/recipe-app/assets/66097371/b52c51f8-56e7-44d7-9a5a-984aa42ad53a)

2023-06-09 20:29 UTC, VICTOR-CHUKWU commented on app/views/recipes/show.html.erb
> +            <%= link_to 'Delete', '#', class: 'action_link' %>
- [ ] I can not delete an item in recipe food kindly fix this 
![Screenshot from 2023-06-09 21-22-41](https://github.com/rica213/recipe-app/assets/66097371/41b5a974-962b-4841-a4b2-d3340fef99dd)

2023-06-09 20:29 UTC, VICTOR-CHUKWU commented on spec/requests/recipes_spec.rb
> +  end
- [ ] some of your tests are failing, kindly fix it
![image](https://github.com/rica213/recipe-app/assets/66097371/9c0d1b3a-20f5-4ea2-8a31-191f11166117)

2023-06-09 21:35 UTC, rica213 commented on app/views/recipes/show.html.erb
> +            <%= link_to 'Delete', '#', class: 'action_link' %>
Hi @VICTOR-CHUKWU, thank you for your insight, however, by our understanding deleting and editing ingredients is not part of the project requirements, it is not mentioned anywhere, **unlike for the food and recipe items**. It is not mentioned anywhere. Kindly confirm this required change 🙏🏽🙏🏽

2023-06-10 08:34 UTC, KDlamini commented on app/views/foods/index.html.erb
> +                    <td><%= button_to 'Delete', food, method: :delete %></td>
Well resolved ✔️

2023-06-10 08:34 UTC, KDlamini commented on app/views/recipes/index.html.erb
> +                <%= button_to 'Remove', recipe, method: :delete %>
Well resolved ✔️

2023-06-10 08:37 UTC, KDlamini commented on app/views/recipes/show.html.erb
> +            <%= link_to 'Delete', '#', class: 'action_link' %>
Well resolved ✔️

2023-06-10 08:47 UTC, KDlamini commented on spec/requests/recipes_spec.rb
> +  end
Well resolved ✔️

![image](https://github.com/rica213/recipe-app/assets/38088818/a21dd16e-0a8b-4f02-893f-da2b394c3289)

2023-06-10 08:56 UTC, KDlamini approved these changes
### Hi team @rica213, @shaaibu7 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes for the Recipe App capstone. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## Highlights 🌞 

✔️  Professional pull request
✔️  All required pages for recipes and foods are present
✔️  Database setup, controllers, models, routes, and views implemented correctly
✔️  The app schema looks similar to the [Entity Relationship Diagram](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_app_erd.png?raw=true)
✔️  App uses RSpec and Capybara testing libraries

# Status: Approved ✔️ 

![oscars-standing-ovation](https://user-images.githubusercontent.com/38088818/164766743-7f6493f3-4506-4331-9678-207bad27e7f5.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 09:10 UTC, rica213 commented
Hi @KDlamini 
Hi @VICTOR-CHUKWU 

Thank you for your time and your insight on improving our project. It is appreciated ❤️ 

Larissa and Shaaibu

2023-06-10 09:11 UTC, merged